# Generated by Django 2.0.7 on 2018-07-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
