# Generated by Django 2.0.7 on 2018-08-04 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180728_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfaction', models.CharField(choices=[('0', 'Very satisfied'), ('1', 'Satisfied'), ('2', 'OK'), ('3', 'Dissatisfied'), ('4', 'Very dissatisfied')], max_length=1)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('locked', models.BooleanField(default=False)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Request')),
            ],
        ),
    ]
