# Generated by Django 2.0.7 on 2018-08-04 05:29

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='feedback_ref',
            field=models.CharField(default=core.models.ref_code_gen, max_length=10, unique=True),
        ),
    ]
