# Generated by Django 2.0.7 on 2018-08-04 10:01

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_request_feedback_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='feedback_ref',
            field=models.CharField(blank=True, default=core.models.ref_code_gen, max_length=10, null=True, unique=True),
        ),
    ]
